Milestone2
ioanniskousis/Calculator pull request #2
Opened 2020-09-09 12:19 UTC by ioanniskousis

## This is Milestone2 for the Calculator Project

- Created components folder with 
    - App.js
    - Display.js
    - ButtonPanel.js
    - Button.js
- Display class has a result prop being a String and default value '0'
- Button class accepts
    - a name prop being a String 
    - a sign prop for their UI 
    - a dblwidth prop to adjust their width
    - and an orange prop for alternative back color

- ButtonPanel class renders five groups each with 4 instances of Button class

<hr />

## [Live Version on Heroku](https://calculator-jgk.herokuapp.com)

2020-09-09 13:36 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there @ioanniskousis :hand: 
Nice job on this milestone so far :clap: 
But before moving on we need to work on some changes.

- [ ] We need to improve the README file with relevant information about your project. Right now it only has the title of the project, all other information belongs to the bootstrap file generated by `create-react-app`. You can read more about making your repository more professional [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). And you can use this template [here](https://github.com/microverseinc/readme-template) for your README file. 
![Screenshot from 2020-09-09 10-28-06](https://user-images.githubusercontent.com/30977845/92604693-2c8a7680-f287-11ea-999f-1d45f1ec86e2.png)

Please kindly submit for code review again after making these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-09-09 13:36 UTC, Torres-ssf commented on src/components/Display.js
> +  }
- [ ] Since the App component does not have any props right now, it's best to declare it as a stateless (functional) component instead of instantiating an empty state.
![Screenshot from 2020-09-09 09-58-15](https://user-images.githubusercontent.com/30977845/92601283-01058d00-f283-11ea-824d-05c491ad025b.png)

2020-09-09 13:48 UTC, ioanniskousis commented on src/components/Display.js
> +  }
### This is from Milestone2 description
App should render the Display and ButtonPanel component. HINT: at this moment App component is a stateless component as it is not fully implemented yet. In order to avoid linter errors 
### **remember to make it a functional component..**

## So I guess you have done a mistake

2020-09-09 13:51 UTC, ioanniskousis commented on src/components/Display.js
> +  }
Since it too early for the README file, because I still don't know the extent of the application, I will do the README file after completing the project

2020-09-09 18:17 UTC, bellom commented on src/components/Display.js
> +  }
Hey @ioanniskousis,  talking about the content of the application, I think it's a react calculator, and you can always update your README file if you need too, don't let us bend the rules 😄 , as we both know that the project requirements are bind to follow by all Microverse students.

It's simple, kindly use the template 👇 

**Kindly update your `README` file and remove unnecessary content**.
Checkout out the below link for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/


**NOTE:**
Your PR could be marked as invalid if you don't have a standard README file;
![image](https://user-images.githubusercontent.com/31897434/92636479-57002200-f2cf-11ea-8c22-73543817392b.png)


**Last observation:** whenever you have any issue with your PR been reviewed by any TSE, kindly message the person directly on slack to tell them their mistake, and I think you're both saying the same thing, thanks for making the changes 👍 .

2020-09-09 18:20 UTC, ioanniskousis commented on src/components/Display.js
> +  }
OK .. in an hour

2020-09-09 18:23 UTC, bellom requested changes
## Hi @ioanniskousis   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-09 18:23 UTC, bellom commented on src/components/Button.js
> +    const { orange } = this.props;
### [Optional]
let's practice [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code.
we could have these lines in one line.
` const { name, sign, ..... } = this.props;`

2020-09-09 18:23 UTC, bellom commented on src/components/ButtonPanel.js
> +            sign="7"
### [Optional]
I think we could make use of two loops to make the Button instead of repeating ourselves. let's practice [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code.

To do this; create an array of symbols and loop through the array using [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to create the ButtonPanel component.

2020-09-10 04:07 UTC, shloch approved these changes
## Hello @ioanniskousis 

Great job with the corrections you made. I see that you switched to functional components all together
![accomplished](https://user-images.githubusercontent.com/40712459/92680740-90fb1380-f323-11ea-94fb-e76f5858646f.jpg)

We're ready to merge this.
Keep up with the good work. 
Happy coding

2020-09-10 04:07 UTC, shloch commented on src/components/Button.js
> +  } = props;
nice

2020-09-10 07:37 UTC, merged