Calculator: Milestone5
ioanniskousis/Calculator pull request #7
Opened 2020-09-11 16:33 UTC by ioanniskousis

## This is the last milestone of the Calculator project

The project was created using the create-react-app model
The default module App was refactored to a class
It renders 2 elements
- Display, held in src/components/Display.js, responsible for the output of the calculations
- ButtonPanel, held in src/components/ButtonPanel.js. Contains all buttons of the calculator

When ButtonPanel is rendered it is passed a reference to the call back function for button click, and it passes it to each of the buttons contained in it. It is the handClick function in the App class

When handleClick in App class is triggered, then the calculate function is called to translate users actions and the result is assigned to the App state triggering rendering

[View Live](https://calculator-jk.herokuapp.com)

2020-09-11 20:32 UTC, bellom requested changes
## Hi @ioanniskousis  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-11 20:32 UTC, bellom commented on src/components/Display.js
> +  const { operation } = props;
### [Optional]
This can be written in one line `const { output, total, operation } = props`

2020-09-11 20:32 UTC, bellom commented on src/logic/operate.js
> +  let divisionByZero = false;
kindly delete these commented codes.

2020-09-11 20:32 UTC, bellom commented on src/logic/operate.js
> +    case '%':
we need to work on the `case: % `
if we click `100` then `%` we are getting zero.

we only need the first number which is `numberOne`

```
   result = numberOne.times('0.01');

```
might work..... 🤔

2020-09-12 06:55 UTC, ioanniskousis commented on src/logic/operate.js
> +    case '%':
### the logic is
- insert first number
- select operation
- insert second number
- select any of these [=, %, /, X, -, +] => Shows results to Display

### for a 30% of 300, should 
  - insert 300
  - select %
  - insert 30
  - select any of these [=, %, /, X, -, +] to see results 90

2020-09-12 07:05 UTC, ioanniskousis commented on src/components/Display.js
> +  const { operation } = props;
# Done

2020-09-12 07:05 UTC, ioanniskousis commented on src/logic/operate.js
> +  let divisionByZero = false;
# Done

2020-09-12 18:36 UTC, suretrust approved these changes
Hi @ioanniskousis, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-09-14 06:58 UTC, merged